# TCL File Generated by Component Editor (示例)
# 2025-01-14
# DO NOT MODIFY unless you know exactly what you are doing.

# 
# request TCL package from ACDS >=16.1 (不同Quartus版本可能有差异)
# 
package require -exact qsys 16.1

#
# module deco7seg_avalon
#
set_module_property NAME              "deco7seg_avalon"
set_module_property DISPLAY_NAME      "deco7seg_avalon"
set_module_property VERSION           "1.0"
set_module_property INTERNAL          false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR            ""
set_module_property DESCRIPTION       "Example 7-seg Avalon component"
set_module_property EDITABLE          true
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY  false
set_module_property REPORT_TO_TALKBACK false

#
# File sets: 指定综合需要用到的 VHDL
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL deco7seg_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE    false

# 把你的 VHDL 添加进来（若文件名就是“deco7seg_avalon.vhd”）
add_fileset_file deco7seg_avalon.vhd VHDL PATH deco7seg_avalon.vhd TOP_LEVEL_FILE

#
# Interfaces
#

# 1) clock_sink - 输入时钟
add_interface clock_sink clock end
set_interface_property clock_sink clockRate        0
set_interface_property clock_sink ENABLED          true
set_interface_property clock_sink EXPORT_OF        ""
set_interface_property clock_sink PORT_NAME_MAP    ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
# VHDL端口: clk
add_interface_port clock_sink clk clk Input 1

# 2) reset_sink - 复位（负有效）
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock  clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED          true
set_interface_property reset_sink EXPORT_OF        ""
set_interface_property reset_sink PORT_NAME_MAP    ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
# VHDL端口: reset_n (active-low)
add_interface_port reset_sink reset_sink_reset reset_n Input 1

# (有些版本也会多加一句: set_interface_property reset_sink RESET_POLARITY ACTIVE_LOW)

# 3) avalon_slave - 用于 Avalon-MM 读写
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits  WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

# VHDL 中的端口:
#   avs_chipselect : in  std_logic;
#   avs_read       : in  std_logic;
#   avs_write      : in  std_logic;
#   avs_address    : in  std_logic_vector(1 downto 0);
#   avs_writedata  : in  std_logic_vector(31 downto 0);
#   avs_readdata   : out std_logic_vector(31 downto 0);
add_interface_port avalon_slave avs_address    avs_address    Input  2
add_interface_port avalon_slave avs_chipselect avs_chipselect Input  1
add_interface_port avalon_slave avs_read       avs_read       Input  1
add_interface_port avalon_slave avs_write      avs_write      Input  1
add_interface_port avalon_slave avs_writedata  avs_writedata  Input  32
add_interface_port avalon_slave avs_readdata   avs_readdata   Output 32

# 4) conduit_end - 把 7段显示管脚 segment 导出到顶层
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""
# VHDL端口: segment(7 downto 0)
add_interface_port conduit_end segment segment Output 8
